name: fusion
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.3.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.6.3
  - ffmpeg=4.3
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipython_genutils=0.2.0
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_core=4.11.2
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.0.149
  - libcups=2.4.2
  - libcurand=10.3.3.53
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql=5.7.24
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1w
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.16
  - python-fastjsonschema=2.16.2
  - pytorch=1.12.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tornado=6.2
  - typing_extensions=4.4.0
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - aiofiles==22.1.0
    - aiosqlite==0.19.0
    - ansi2html==1.8.0
    - anyio==3.7.0
    - arrow==1.2.3
    - attrs==23.1.0
    - beautifulsoup4==4.7.1
    - beautifultable==0.7.0
    - black==23.3.0
    - bleach==6.0.0
    - boto3==1.33.13
    - botocore==1.33.13
    - cached-property==1.5.2
    - cachetools==5.3.1
    - ccimport==0.4.2
    - certifi==2024.8.30
    - chardet==4.0.0
    - click==6.7
    - colorama==0.4.6
    - configargparse==1.5.5
    - cryptography==45.0.4
    - cumm-cu113==0.4.10
    - cycler==0.11.0
    - dash==2.11.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.7.0
    - descartes==1.1.0
    - docker==3.6.0
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - evalai==1.3.18
    - exceptiongroup==1.1.1
    - faiss-gpu==1.7.2
    - fastjsonschema==2.17.1
    - fire==0.5.0
    - flake8==3.9.2
    - flash-attn==1.0.7
    - flask==2.2.5
    - fonttools==4.38.0
    - fqdn==1.5.1
    - fvcore==0.1.5.post20221221
    - google-auth==2.21.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.56.0
    - idna==2.10
    - imageio==2.31.1
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - iopath==0.1.10
    - ipykernel==6.16.2
    - ipython==7.34.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - joblib==1.3.1
    - jsonpointer==3.0.0
    - jupyter-console==6.6.3
    - jupyter-core==4.12.0
    - jupyter-events==0.6.3
    - jupyter-server==1.24.0
    - jupyter-server-fileid==0.9.3
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.5
    - jupyterlab==3.6.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kaggle==1.6.17
    - kiwisolver==1.4.4
    - lark==1.1.5
    - llvmlite==0.36.0
    - lxml==4.6.2
    - lyft-dataset-sdk==0.0.8
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.5.2
    - mccabe==0.6.1
    - mdurl==0.1.2
    - mistune==3.0.2
    - mmcls==0.25.0
    - mmcv-full==1.6.0
    - mmdet==2.24.0
    - mmsegmentation==0.29.1
    - model-index==0.1.11
    - motmetrics==1.1.3
    - mypy-extensions==1.0.0
    - nbclassic==1.0.0
    - nbclient==0.7.4
    - nbconvert==7.6.0
    - networkx==2.2
    - ninja==1.11.1
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numba==0.53.0
    - nuscenes-devkit==1.1.10
    - oauthlib==3.2.2
    - open3d==0.17.0
    - opencv-python==4.8.0.74
    - opendatalab==0.0.9
    - openmim==0.3.9
    - ordered-set==4.1.0
    - packaging==23.1
    - pandas==1.3.5
    - pathspec==0.11.1
    - pccm==0.4.7
    - platformdirs==3.8.0
    - plotly==5.15.0
    - pluggy==1.2.0
    - plyfile==0.9
    - portalocker==2.7.0
    - prettytable==3.7.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - protobuf==3.20.3
    - psutil==5.9.5
    - ptflops==0.7
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybind11==2.10.4
    - pycocotools==2.0.6
    - pycodestyle==2.7.0
    - pycryptodome==3.18.0
    - pyflakes==2.3.1
    - pygments==2.15.1
    - pyopenssl==25.1.0
    - pyparsing==3.1.0
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - pytest==7.4.0
    - python-dateutil==2.7.3
    - python-json-logger==3.0.1
    - python-slugify==8.0.4
    - pytorch3d==0.7.4
    - pytz==2023.3
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - requests==2.25.1
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.4.2
    - rsa==4.9
    - s3transfer==0.8.2
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - send2trash==1.8.2
    - shapely==1.8.5
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - spconv-cu113==2.3.6
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - terminaltables==3.1.10
    - text-unidecode==1.3
    - thop==0.1.1-2506192153
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - torch-geometric==2.3.1
    - tqdm==4.65.0
    - traitlets==5.9.0
    - trimesh==2.35.39
    - typed-ast==1.5.4
    - typing-extensions==4.7.0
    - uri-template==1.3.0
    - urllib3==2.0.7
    - validators==0.12.6
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.7
    - y-py==0.6.2
    - yacs==0.1.8
    - yapf==0.40.1
    - ypy-websocket==0.8.4
    - zipp==3.15.0
